// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bccjymakoczdswgflctv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjY2p5bWFrb2N6ZHN3Z2ZsY3R2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1NzE0NjYsImV4cCI6MjA1NzE0NzQ2Nn0.Hiy1PCICQBOaEDaqQPa4jzEt7lN9mMr0oapQCin7hcg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);